default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Task_Management_System_development
test:
  <<: *default
  database: Task_Management_System_test
  host: 0.0.0.0

production:
  <<: *default
  database: Task_Management_System_production
