default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_development
test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_test
  host: 0.0.0.0

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_production
